### ISSUE TITLE
alpine-based images have /usr/local/apache2 with incorrect group

### ISSUE THREAD

**Issue by marosivanco** [docker-library/httpd#100]
Start alpine based container with bash:
`docker run -it  httpd:2.4.33-alpine bash`
then in the container run:
`ls -la`
which prints:
```
drwxr-xr-x   12 www-data www-data      4096 Jul  6 15:40 .
drwxr-xr-x   10 root     root          4096 Jul  6 15:38 ..
drwxr-xr-x    2 root     root          4096 Jul  6 15:40 bin
drwxr-xr-x    2 root     root          4096 Jul  6 15:40 build
drwxr-xr-x    2 root     root          4096 Jul  6 15:40 cgi-bin
drwxr-xr-x    4 root     root          4096 Jul  6 15:40 conf
drwxr-xr-x    3 root     root          4096 Jul  6 15:40 error
drwxr-xr-x    2 root     root          4096 Jul  6 15:40 htdocs
drwxr-xr-x    3 root     root          4096 Jul  6 15:40 icons
drwxr-xr-x    2 root     root          4096 Jul  6 15:40 include
drwxr-xr-x    2 root     root          4096 Jul  6 15:40 logs
drwxr-xr-x    2 root     root          4096 Jul  6 15:40 modules
```
The group of subdirectorries is not www-data, as in the case of non-alpine images:
`docker run -it  httpd:2.4.33 bash`
`ls -la`
prints:
```
drwxr-sr-x 12 www-data www-data 4096 Jun 26 22:38 .
drwxrwsr-x 14 root     staff    4096 Jun 26 22:35 ..
drwxr-sr-x  2 root     www-data 4096 Jun 26 22:38 bin
drwxr-sr-x  2 root     www-data 4096 Jun 26 22:38 build
drwxr-sr-x  2 root     www-data 4096 Jun 26 22:38 cgi-bin
drwxr-sr-x  4 root     www-data 4096 Jun 26 22:38 conf
drwxr-sr-x  3 root     www-data 4096 Jun 26 22:38 error
drwxr-sr-x  2 root     www-data 4096 Jun 26 22:38 htdocs
drwxr-sr-x  3 root     www-data 4096 Jun 26 22:38 icons
drwxr-sr-x  2 root     www-data 4096 Jun 26 22:38 include
drwxr-sr-x  2 root     www-data 4096 Jun 26 22:38 logs
drwxr-sr-x  2 root     www-data 4096 Jun 26 22:38 modules
```

**Comment by wglambert** [comment]
Both dockerfiles have the same `chown` syntax
https://github.com/docker-library/httpd/blob/eaf4c70fb21f167f77e0c9d4b6f8b8635b1cb4b6/2.4/Dockerfile#L6-L9
https://github.com/docker-library/httpd/blob/eaf4c70fb21f167f77e0c9d4b6f8b8635b1cb4b6/2.4/alpine/Dockerfile#L12-L15

As for the directory's contents: that ownership might be innate from the different NGHTTP2 versions used. Debian is 1.18.1-1 and Alpine is 1.32.0-r0, or some other difference in installation methods between Debian and Alpine

Is there any anomalous behavior or issues from the change in group ownership for these files?

**Comment by tianon** [comment]
Given that this doesn't seem to cause any ill effects, I'm going to close.

If there's a simple fix, we'd love to make it (but probably not just doing `chown` after the full install -- understanding why we're getting different behavior in the two environments first is important).

**Comment by marosivanco** [comment]
@tianon, is there a reason to use `www-data` in the first place?

**Comment by tianon** [comment]
See https://github.com/docker-library/httpd/issues/10 for more discussion around that point.
