### ISSUE TITLE
docker images could use multi-stage builds

### ISSUE THREAD

**Issue by marosivanco** [docker-library/httpd#101]
There is a lot going on in the httpd Dockerfile: install build/runtime dependencies, download sources, build httpd...
The images could benefit from [multi stage builds](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds) (available from Docker 17.05).
The basic idea is to separate the whole process into two stages:
**Build** - which can create temp image with build-time dependencies, download sources, check sum, build.

**(unnamed)** - which installs run-time dependencies and copies built artefacts from the **Build** stage.

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/issues/3383
