### ISSUE TITLE
SSL/HTTPS documentation incorrect

### ISSUE THREAD

**Issue by tdrake-com** [docker-library/httpd#108]
Following the current instructions found in the main page/readme under the section entitled Configuration:SSL/HTTPS results in a server that doesn't start. There are two simple changes that are required:
Uncomment the following two lines in httpd.conf:
```
#LoadModule socache_shmcb_module libexec/apache2/mod_socache_shmcb.so
#LoadModule ssl_module libexec/apache2/mod_ssl.so
```

This can be done by adding the following lines to your Dockerfile:
```
RUN sed -i .bkup -e 's/^#\(Include .*httpd-ssl.conf\)/\1/' \
         -e 's/^#\(LoadModule .*mod_ssl.so\)/\1/' \
         -e 's/^#\(LoadModule .*mod_socache_shmcb.so\)/\1/' \
	    ./conf/httpd.conf
```

Please note that I believe that this is similar to, if not identical to issues #61, #49, and #1. But this solution is the simplest to resolve this issue.

**Comment by tianon** [comment]
Good call, I've opened https://github.com/docker-library/docs/pull/1280 to update this.  Thanks for doing the research to figure out what was missing! :+1:
