### ISSUE TITLE
mpm_worker support

### ISSUE THREAD

**Issue by oliver-schoenherr** [docker-library/httpd#11]
Is there any chance to support the mpm_worker Mode?

**Comment by boxxxie** [comment]
it would be great if at least someone could comment on this

**Comment by yosifkit** [comment]
I think this would just need an [`--enable-mpms-shared=all`](https://httpd.apache.org/docs/2.4/mpm.html) added to the [configure line](https://github.com/docker-library/httpd/blob/fe74fda1ef0263751b3f12dbac3b9043ba1c1651/2.4/Dockerfile#L52)?  Then users just need to change the "LoadModule" directive in the config to load the mpm they desire.  Would this affect the default use case?
