### ISSUE TITLE
TLS 1.3 not supported due to old libssl

### ISSUE THREAD

**Issue by koehn** [docker-library/httpd#116]
I cannot enable TLSv1.3 on my server, because the version of `libssl` is 1.1.0f, and 1.1.1 or newer is required for TLSv1.3 support. A quick search of the [Debian Package site](https://packages.debian.org/search?keywords=libssl) indicates that they only support `libssl1.1.1` on "sid" right now. I'm not sure if you want to compile libssl and include it yourself, or how to you want to handle it, but it would be great to have full TLSv1.3 support in the Docker image. 

Thanks for all the hard work you do. It's really appreciated.

**Comment by yosifkit** [comment]
Yeah we don't really want to also compile openssl from source, so we'll have to wait until it can be installed in a stable distribution of Debian.

**Comment by koehn** [comment]
FWIW OpenSSL 1.1.1 is now included in Debian Buster, which should be released in the first half of 2019. I'm running a version of your Dockerfile based on `debian:buster-slim` and TLS 1.3 and 1.2 are working fine.

**Comment by J0WI** [comment]
This will be fixed in #124
