### ISSUE TITLE
upgrade lua-libs

### ISSUE THREAD

**Issue by MarcoSchaar** [docker-library/httpd#119]
Hi,
please upgrade lua-libs
kind regards
Marco

**Comment by tianon** [comment]
If you're referring to the Debian-based variant, our Lua comes from Debian, so this update would need to happen there: https://github.com/docker-library/httpd/blob/49a437c5bdab922c65caa8ff157fc250be4479b4/2.4/Dockerfile#L51

If you're referring to the Alpine-based variant, it's the same situation, but with Alpine's Lua package instead: https://github.com/docker-library/httpd/blob/49a437c5bdab922c65caa8ff157fc250be4479b4/2.4/alpine/Dockerfile#L55

(In other words, the only way we could change this right now would be to build Lua from source, which isn't really something we're keen on doing without a _really_ strong justification.)

**Comment by tianon** [comment]
Closing due to lack of justification for an update.  If there's a strong reason why it's important for us to upgrade (especially in the form of an explicit recommendation from HTTPd upstream), please let us know and we'll reconsider! :+1:
