### ISSUE TITLE
httpd process crashes when using SSL: "Illegal instruction"

### ISSUE THREAD

**Issue by ovk** [docker-library/httpd#128]
Image: `httpd:alpine` (v2.4.38)
CPU: `Intel(R) Celeron(R) CPU J3455 @ 1.50GHz`
CPU Flags: `fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm 3dnowprefetch cpuid_fault cat_l2 ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust smep erms mpx rdt_a rdseed smap clflushopt intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts arch_capabilities`

When running Apache with SSL enabled, httpd processes frequently crash with the following message:

```
[Mon Apr 01 13:21:49.170358 2019] [core:notice] [pid 1:tid 140156675435368] AH00051: child pid 332 exit signal Illegal instruction (4), possible coredump in /usr/local/apache2
```

No issues when the exact same image ran in the same configuration on a VM without AES-NI.

**Comment by ovk** [comment]
@wglambert, I'm running Nextcloud setup, where httpd acts as static web server and a fastcgi proxy. So the complete setup is quite cumbersome to reproduce. 

Here is my httpd config file: https://pastebin.com/rvUCrK0R

And I use the following Dockerfile to build the image:

```dockerfile
FROM httpd:alpine

RUN apk --no-cache --no-progress upgrade && \
    apk --no-cache --no-progress add openssl && \
    openssl dhparam -out /etc/ssl/dhparam.pem 2048

COPY httpd.conf /usr/local/apache2/conf/httpd.conf
```

This is the line from logs when httpd starts:

```
Apache/2.4.38 (Unix) OpenSSL/1.1.1b configured
```

I was hoping to grab a core file to at least see the stack trace, but for some reason it is not generated in this case. I checked that `ulimit -c` is `unlimited` and set `/proc/sys/kernel/core_pattern` to write files under the `/tmp`. When I do something like `kill -s SIGSEGV $$` inside the container - the core file is generated; however, when httpd process crashes I see no core file.

If you have any ideas how I could debug this issue, please let me know.

**Comment by ovk** [comment]
I was able to get core dump:

```
warning: .dynamic section for "/usr/lib/libssl.so.1.1" is not at the expected address (wrong library or version mismatch?)
Core was generated by `httpd -DFOREGROUND'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f93c3da265b in apr_brigade_flatten () from /usr/lib/libaprutil-1.so.0
[Current thread is 1 (LWP 210)]
```

**Comment by wglambert** [comment]
It might be related to https://bugs.alpinelinux.org/issues/10163

Do you encounter the error on non-alpine?

**Comment by ovk** [comment]
I don't think it is related to the bug you mentioned, because in my case OpenSSL versions look consistent:

```
bash-4.4# openssl version
OpenSSL 1.1.1b  26 Feb 2019
bash-4.4# strings /lib/libssl.so.1.1  | grep "OpenSSL 1.1.1"
OpenSSL 1.1.1b  26 Feb 2019
bash-4.4# strings /lib/libcrypto.so.1.1 | grep "OpenSSL 1.1.1" 
OpenSSL 1.1.1b  26 Feb 2019
```

I did not try non-alpine and trying it on the physical machine where the issue occurs would be quite difficult.

From the core dump it looks like the issue is related to HTTP2, so I tried disabling it and so far the issue seems to disappear.

**Comment by tianon** [comment]
The fact that the `SIGILL` happens in `/usr/lib/libaprutil-1.so.0` is the real clue here -- there's something borked with the APR Alpine build (we don't build that, we install it via `apk` from Alpine), and there's really nothing more we can do except suggest you file a new issue with Alpine to have that package updated/fixed.

Closing since this is not something we can really fix in the image itself (and it needs to happen upstream in Alpine itself instead).

**Comment by ovk** [comment]
Thank you @tianon, issue opened: https://bugs.alpinelinux.org/issues/10199
