### ISSUE TITLE
Latest image for s390x

### ISSUE THREAD

**Issue by alicefr** [docker-library/httpd#129]
Hi,

I'm using the `httpd` for s390x and I tried to pull the latest image but it got this:
```sh
$ docker pull httpd:latest
latest: Pulling from library/httpd
no matching manifest for unknown in the manifest list entries
$ docker pull httpd:2.4   
2.4: Pulling from library/httpd
no matching manifest for unknown in the manifest list entries
$ docker pull httpd:2  
2: Pulling from library/httpd
no matching manifest for unknown in the manifest list entries
```
If I give explicitly the s390x tag than I can pull the image `s390x/httpd`. Do you have any issue with the multi-arch manifest?

Thanks for the help!

**Comment by tianon** [comment]
It's built successfully (https://doi-janky.infosiftr.net/job/multiarch/job/s390x/job/httpd/), and appears in the manifest list:

```console
$ manifest-tool inspect httpd | grep s390x
7           -    Arch: s390x
```

So I think this is just an instance of https://github.com/docker-library/official-images/issues/3835 following https://github.com/docker-library/official-images/pull/5659.

**Comment by alicefr** [comment]
Thanks! Now, the issue is solved.
