### ISSUE TITLE
Add support for mod_brotli

### ISSUE THREAD

**Issue by epicoxymoron** [docker-library/httpd#132]
This is definitely a request, rather than a bug, but it would be great if mod_brotli were supported in this image.

[Here](https://gist.github.com/rcanavan/b799331ea2008860f8e1f02b8b5be42f)'s an example of a hacked-up Dockerfile that includes Brotli support (from someone complaining about its resource usage) -- that was over a year ago, though.

[This](https://ayesh.me/apache-brotli) may (or may not) be a better way to do that now.

**Comment by tianon** [comment]
Given that it's not an official module distributed by httpd upstream, we're
not going to include it in the image.

However, it should be possible to build an image that's FROM this one that
compiles it.  For help with that, I'd recommend trying the forums, stack
overflow, or the Docker community slack.

**Comment by epicoxymoron** [comment]
I would include the [httpd documentation](https://httpd.apache.org/docs/2.4/mod/mod_brotli.html) as an "official" source.  It is correct to say that it's not distributed upstream because it's [officially an "Extension" module](https://httpd.apache.org/docs/2.4/mod/module-dict.html#Status) rather than "Base", but it's not "External", which is a direct claim of first-party support, as I understand it.  `mod_ssl` is [also an Extension module](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html), for example, but it's included in this image.

There are obvious benefits to consumers of this image, and an equally-obvious maintenance burden.  Can you help me understand the objection to the inclusion of this module, given its appearance in official documentation?  As evidence for its "supportedness", it appears that [questions](http://mail-archives.apache.org/mod_mbox/httpd-users/201806.mbox/%3C796476ff-4052-1324-7fb2-3f9a50a8c1f6@wanadoo.fr%3E) received via the mailing lists are being answered; I couldn't find evidence of any punting.

**Comment by phy25** [comment]
1) This Dockerfile doesn't explicitly define which module should be installed:

https://github.com/docker-library/httpd/blob/75e85910d1d9954ea0709960c61517376fc9b254/2.4/Dockerfile#L112-L116

2) However, which module will be complied depends on existence of their dependency:

https://github.com/docker-library/httpd/blob/75e85910d1d9954ea0709960c61517376fc9b254/2.4/Dockerfile#L44-L59

3) Looks like some of the decision of the libraries comes from Debian's package:

https://github.com/docker-library/httpd/blob/75e85910d1d9954ea0709960c61517376fc9b254/2.4/Dockerfile#L40-L41

4) In the latest version of [their control file](https://salsa.debian.org/apache-team/apache2/blob/master/debian/control), they have `libbrotli-dev`. See the commit: https://salsa.debian.org/apache-team/apache2/commit/5a0afb5a83587da7fbb958666a90cd3743b1a7a9

5) However, when choosing which module (and which dependency library) should be installed, one important fact is size. I have no idea about the size of this library.

**Comment by epicoxymoron** [comment]
To point (5), `libbrotli-dev` is [66 KB installed](https://packages.debian.org/sid/libbrotli-dev).

**Comment by tianon** [comment]
Ah!  Given it's a core module (and the size impact is low), I agree we should work to get it working properly.

Just to clarify, we reference Debian mostly as a reference for dependencies (since those aren't always as obvious as `libbrotli-dev` for enabling functionality). :+1:

**Comment by epicoxymoron** [comment]
Works like a charm.  Thank you!
