### ISSUE TITLE
Missing a2enmod executable?

### ISSUE THREAD

**Issue by ORESoftware** [docker-library/httpd#135]
I have this:

```Dockerfile
FROM httpd:2.4 AS apache_build
RUN a2enmod --version
```

I get this:

```
/bin/sh: 1: a2enmod: not found
```

I thought this utility was supposed to come with apache2/httpd?

**Comment by tianon** [comment]
`a2enmod` isn't included because it's not part of a standard upstream `httpd` distribution, which is what this image provides (it's something invented/included by Debian; see https://salsa.debian.org/apache-team/apache2/blob/bd132df6696eab5d11758ea9beb365eabd13b6d8/debian/a2enmod).

**Comment by ORESoftware** [comment]
When I run this:

```
RUN apt-get install -y apache2
```

now the executable is available, so something is missing from the Dockerfile?

**Comment by tianon** [comment]
That's installing Debian's Apache package -- if you want to use that, you
don't want "FROM httpd" and instead simply want "FROM debian:stretch".
