### ISSUE TITLE
Install and load evasive

### ISSUE THREAD

**Issue by kyauaa** [docker-library/httpd#141]
Hi,
I found that this version did not include a2enmod.
So what is the practical way to install and load evasive module? Thanks.

**Comment by tianon** [comment]
> I found that this version did not include a2enmod.

Duplicate of https://github.com/docker-library/httpd/issues/135

> So what is the practical way to install and load evasive module? Thanks.

To get `mod_evasive` working with this Docker image, you'll need to build `mod_evasive` from source and enable it via an Apache configuration file.
