### ISSUE TITLE
use SIGWINCH to gracefully shut down on stop

### ISSUE THREAD

**Issue by johnl** [docker-library/httpd#145]
Currently, stopping the containers causes docker to send the default TERM signal to apache, which immediately kills all child processes and exits.

Sending the WINCH signal instead tells apache to gracefully shut down instead (stop accepting new requests, wait for existing requests in progress to finish, then exit)

https://httpd.apache.org/docs/current/stopping.html#gracefulstop

`STOPSIGNAL WINCH`

**Comment by wglambert** [comment]
Closing as duplicate of https://github.com/docker-library/php/issues/877

**Comment by tianon** [comment]
This one isn't completely a dupe of that one (different builds of `httpd`); implemented in https://github.com/docker-library/httpd/commit/3ebff8dadf1e38dbe694ea0b8f379f6b8bcd993e, thanks! :+1:
