### ISSUE TITLE
httpd: 2.4.41:  ping, curl and wget is not working

### ISSUE THREAD

**Issue by kesinikandasamy** [docker-library/httpd#149]
Hi,

Some basic commands like ping, curl and wget is not working within this container.
Any clue on how we can fix this ? Is there any alternative for these commands that can be used within this container

Thanks & Regards
Kesini

**Comment by kesinikandasamy** [comment]
Hi, 
Thanks for your suggestion.  apt-get update in the container gives the below error due to which i am not able to install any util in this container

================
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
================

any clue ?

**Comment by yosifkit** [comment]
@kesinikandasamy ensure that you are running as root. You'll have to do that via docker (`docker run --user root:root`) since there is no sudo in the image and no root password
