### ISSUE TITLE
Add `apr-util-dbm_db` package to the Alpine variant

### ISSUE THREAD

**Issue by lubo** [docker-library/httpd#153]
` mod_dav` requires setting `DavLockDB` directive, which depends on `apr-util-dbm_db` on Alpine. Without it, the server returns status code 500 when a client uploads a file and logs the error like this:

```
[Sat Dec 28 13:11:12.463663 2019] [dav_fs:crit] [pid 9:tid 139762123082528] (20019)DSO load failed: AH00576: The DBM driver could not be loaded
[Sat Dec 28 13:11:12.463682 2019] [dav:error] [pid 9:tid 139762123082528] [client 10.0.48.2:40280] The locks could not be queried for verification against a possible "If:" header.  [500, #0]
[Sat Dec 28 13:11:12.463689 2019] [dav:error] [pid 9:tid 139762123082528] [client 10.0.48.2:40280] Could not open the lock database.  [500, #400]
[Sat Dec 28 13:11:12.463693 2019] [dav:error] [pid 9:tid 139762123082528] (20019)DSO load failed: [client 10.0.48.2:40280] Could not open property database.  [500, #1]
```

Installing `apr-util-dbm_db` fixes the problem.

**Comment by minfrin** [comment]
For those arriving via google, the error handling is fixed in apr-util here:

http://svn.apache.org/viewvc?rev=1891018&view=rev

and for httpd here:

http://svn.apache.org/viewvc?rev=1891019&view=rev
