### ISSUE TITLE
Following the doc on the httpd container page creates a wrong httpd.conf under Windows

### ISSUE THREAD

**Issue by advapiIT** [docker-library/httpd#157]
Hello,
I've found this issue trying to edit the httpd.conf during my building of a docker image.
What happens is described [here ](https://stackoverflow.com/questions/60741614/ah00534-httpd-configuration-error-no-mpm-loaded-when-copying-my-own-httpd-co)(I think it was a fault of mine while creating the image, so that, I asked on StackOverflow)

The doc I refer to is [this one ](https://hub.docker.com/_/httpd)

What happens is that when I execute (from cmd or poweshell, under Windows)

```$ docker run --rm httpd:2.4 cat /usr/local/apache2/conf/httpd.conf > my-httpd.conf```

It generates me for httpd:latest a file of 42Kb.
While if I copy if, from a docker image, taken from the container, using shell, it's around 21kb

If I use the 42kb file (NotePad++ tells its Windows (CR LF) - USC2-LE BOM) when I start the container I got **httpd: Configuration error: No MPM loaded** 

If I use the 20kb file (Unix LF - UTF8) it works.

Why does this happen? Can you please somehow update the documentation so that others won't fall in my situation?

Thanks in advance

**Comment by wglambert** [comment]
Copying the file from Linux to Windows formats the file with MS-DOS [line endings](https://en.wikipedia.org/wiki/Newline#Issues_with_different_newline_formats) which makes the file invalid on Linux
>Furthermore, programs other than text editors may not accept a file, e.g. some configuration file, encoded using the foreign newline convention, as a valid file.

Theres nothing we can fix for this at the Dockerfile level, this is more suited for https://github.com/docker/for-win/issues
Linux Containers on Windows (LCOW) is an [experimental feature](https://success.docker.com/article/are-linux-containers-on-windows-supported) not ready for production. 
https://docs.docker.com/v17.09/docker-for-windows/install/#download-docker-for-windows
>. . . To run Docker Windows containers in production, see instructions for installing Docker EE on Windows Server 2016. To run Docker Linux containers in production, see instructions for installing Docker on Linux.

**Comment by letardigrade** [comment]
> 
> 
> Hello,
> I've found this issue trying to edit the httpd.conf during my building of a docker image.
> What happens is described [here ](https://stackoverflow.com/questions/60741614/ah00534-httpd-configuration-error-no-mpm-loaded-when-copying-my-own-httpd-co)(I think it was a fault of mine while creating the image, so that, I asked on StackOverflow)
> 
> The doc I refer to is [this one ](https://hub.docker.com/_/httpd)
> 
> What happens is that when I execute (from cmd or poweshell, under Windows)
> 
> `$ docker run --rm httpd:2.4 cat /usr/local/apache2/conf/httpd.conf > my-httpd.conf`
> 
> It generates me for httpd:latest a file of 42Kb.
> While if I copy if, from a docker image, taken from the container, using shell, it's around 21kb
> 
> If I use the 42kb file (NotePad++ tells its Windows (CR LF) - USC2-LE BOM) when I start the container I got **httpd: Configuration error: No MPM loaded**
> 
> If I use the 20kb file (Unix LF - UTF8) it works.
> 
> Why does this happen? Can you please somehow update the documentation so that others won't fall in my situation?
> 
> Thanks in advance

Big thanks

**Comment by irbian** [comment]
I found this problem too. Maybe add a note along the lines of "Beware that this command generate a file with the wrong encoding under windows, see https://github.com/docker-library/httpd/issues/157"

In my case the solution was to reencode the extracted file to utf-8 following https://stackoverflow.com/a/60680988
