### ISSUE TITLE
where to copy my php file

### ISSUE THREAD

**Issue by rafiql** [docker-library/httpd#16]
This information is not clear here where to copy my php files!!!

if I have pulled httpd image in my server then how i create my container?
I have my .php files inside /etc/ussd-files

docker run -d -p 7007:80 -v /etc/ussd-files:/var/www/html httpd. is this correct? In browser I am getting html code not the translated web page.

**Comment by yosifkit** [comment]
The httpd contianer only contains `httpd` and not a php interpreter.  If you want httpd/apache2 with a php interpreter, you would need one of the `apache` tags in the [`php` repo](https://hub.docker.com/_/php/).

**Comment by rafiql** [comment]
thanks.
