### ISSUE TITLE
Why apr-dev and apr-util-dev are in runDeps in alpine?

### ISSUE THREAD

**Issue by keioni** [docker-library/httpd#160]
Hi,

In the Alpine version of Dockerfile, the development packages apr-dev and apr-util-dev were included in runDeps.
I think these packages are used to build httpd and are not needed at runtime.
What is the reason for the current settings?

I tried changing it as follows:
* move `apr-dev` and `apr-util-dev` to .build-deps
* add `apr` and `apr-util` to runDeps

As a result, the image size has been reduced to 56.5MB (and if Perl is not required, can be reduced to 22.3MB).

The Dockerfile used for the test is here.
https://github.com/keioni/httpd/blob/master/2.4/alpine/Dockerfile

This seems to be working correctly.
Could someone please test and make sure?

Thanks.

**Comment by yosifkit** [comment]
They were added to fix apxs: https://github.com/docker-library/httpd/pull/7

**Comment by keioni** [comment]
I understood.
Are you planning to remove the development package?
I feel that 100MB is too large for an alpine image, and I think a smaller image size is better than that.
