### ISSUE TITLE
Alpine v3.12 is not supported by AWS

### ISSUE THREAD

**Issue by harzbecher** [docker-library/httpd#162]
Hi, Recently I noticed that httpd:alpine was upgraded to v3.12, but this version is not yet supported by AWS, so I'm not able to run my containers anymore. I don't see a way to select a previous version of Alpine by keeping httpd in the latest version (2.4.43).

Is there any way to use httpd 2.4.43 with Alpine v3.11?

This is the error I'm getting from AWS: **UnsupportedImageError: The operating system 'alpine' version 'v3.12' is not supported.**

**Comment by tianon** [comment]
To clarify, this is when trying to scan the image with ECR, not when trying to run, right?  There shouldn't be any restrictions on what you're able to *run* on AWS, especially not OS version restrictions.

If you want to get the content digest of the older Alpine 3.11-based image, you probably want to check out https://github.com/docker-library/repo-info/commits/master/repos/httpd/remote/alpine.md, and I believe https://github.com/docker-library/repo-info/commit/c672430802b36d6c36a555eee6f908e1b6b3c151#diff-23f311476f33e5bdc059f2522f929ed9 in particular is probably what you're after:

```console
$ docker pull httpd@sha256:30a98fa70cb11a4b388328c8512c5cd2528b3c0bd4c4f02def164f165cbb153e
sha256:30a98fa70cb11a4b388328c8512c5cd2528b3c0bd4c4f02def164f165cbb153e: Pulling from library/httpd
cbdbe7a5bc2a: Already exists 
d675277ceb41: Pull complete 
05d6ddf7a817: Pull complete 
0da22ef96744: Pull complete 
5f950d770af2: Pull complete 
Digest: sha256:30a98fa70cb11a4b388328c8512c5cd2528b3c0bd4c4f02def164f165cbb153e
Status: Downloaded newer image for httpd@sha256:30a98fa70cb11a4b388328c8512c5cd2528b3c0bd4c4f02def164f165cbb153e
docker.io/library/httpd@sha256:30a98fa70cb11a4b388328c8512c5cd2528b3c0bd4c4f02def164f165cbb153e
$ docker run --rm httpd@sha256:30a98fa70cb11a4b388328c8512c5cd2528b3c0bd4c4f02def164f165cbb153e cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.11.6
PRETTY_NAME="Alpine Linux v3.11"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

**Comment by harzbecher** [comment]
Awesome!, thanks @tianon that's what I was looking for, regarding the clarification, you are right, ECR is not able to scan the image and due to internal company policies that specific images are being blocked from the registry.

**Comment by harzbecher** [comment]
Thanks! The issue was solved by using this image: httpd@sha256:30a98fa70cb11a4b388328c8512c5cd2528b3c0bd4c4f02def164f165cbb153e
