### ISSUE TITLE
/usr/bin/apr-1-config not found issue when building mod_auth_mellon using httpd:2.4.43-alpine

### ISSUE THREAD

**Issue by wonkyto** [docker-library/httpd#164]
I'm not sure this is the right place to mention this - please forgive me if it isn't.

We were previously building mod_auth_mellon using httpd:2.4.41-alpine without problem.

Yesterday when we pulled the latest httpd:alpine (2.4.43-alpine) we received this error:

```
config.status: creating config.h
  cd xmlsec1-1.2.30 && \
/usr/local/apache2/bin/apxs -Wc,"-std=c99   -I/usr/local/include -I/usr/include/libxml2 -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -I/usr/local/include/xmlsec1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -DHAVE_LASSO_UTILS_H  -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include  -g -O2" -Wl,"-lssl -lcrypto  -L/usr/local/lib -llasso  -lcurl  -lglib-2.0 -lintl " -Wc,-Wall -Wc,-g -c mod_auth_mellon.c auth_mellon_cache.c auth_mellon_config.c auth_mellon_cookie.c auth_mellon_diagnostics.c auth_mellon_handler.c auth_mellon_util.c auth_mellon_session.c auth_mellon_httpclient.c
  cd xmlsec1-1.2.30 && \
apxs:Error: /usr/bin/apr-1-config not found!.
make: *** [Makefile:45: mod_auth_mellon.la] Error 1
```

Now I know this isn't the place to talk about mod_auth_mellon, but it would appear something has changed in regard to the availability of /usr/bin/apr-1-config between the httpd:alpine versions?

Thanks for your time.

**Comment by phy25** [comment]
Could you provide a Dockerfile so people could at least reproduce your issue?

**Comment by tianon** [comment]
This was an intentional change/fix in https://github.com/docker-library/httpd/pull/163 -- you'll want to manually `apk add --no-cache apr-dev` in your `Dockerfile` (optionally with `--virtual` so you can easily/cleanly `apk del` after you build your module).

**Comment by wonkyto** [comment]
Thank you for your quick reply!

**Comment by wonkyto** [comment]
I'll also add (for anyone else coming across this thread) I also needed `apr-util-dev` as `/usr/bin/apu-1-config` was also required and missing.

**Comment by keioni** [comment]
My environment includes that.

```
apk info -L apr-util-dev | grep apu-1-config
usr/bin/apu-1-config
```
