### ISSUE TITLE
disable pidfile for read-only filesystem

### ISSUE THREAD

**Issue by prasad-1210** [docker-library/httpd#166]
Hello,

Please advise on how to start apache without PidFile on read-only filesystem container.

$ **docker run -ti --rm --read-only httpd:latest**
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Thu Aug 06 11:24:11.244759 2020] [core:error] [pid 1:tid 139675808650368] (30)**Read-only file system: AH00099: could not create /usr/local/apache2/logs/httpd.pid**
[Thu Aug 06 11:24:11.245287 2020] [**core:error**] [pid 1:tid 139675808650368] AH00100: **httpd: could not log pid to file /usr/local/apache2/logs/httpd.pid**

Thanks,
Prasad.CH

**Comment by tianon** [comment]
I imagine you can probably set `PidFile` to something like `/dev/null`.  What I usually do though is just add a `--tmpfs /run` to my read-only containers and have them store files like this under `/run` instead (like they would be on a "normal" non-Docker host).

**Comment by prasad-1210** [comment]
Thank you @tianon for your suggestion.

Definitely this is the first thing came to my mind and I've tried to set PidFile to `/dev/null `but it fails with Error
```
20014 Internal Server Error (specific information not available): AH00058: Error retrieving pid file /dev/null
AH00059 Remove it before continuing if it is corrupted
```

i suspect it is due to reason that httpd tries to acquire mutex lock on file which is not allowed on /dev/null device.


So, only workable solution i could see is to mount a `/tmp` that works so far. But, problem is it is not always possible to have access to write to host filesystem.

**Comment by tianon** [comment]
Hmm, you could probably (ab)use `/dev/shm` with something like `/dev/shm/httpd.pid`, but an explicit `tmpfs` seems like a more appropriate solution.

**Comment by prasad-1210** [comment]
with /dev/shm works like charm. Not sure if there are any downsides of using `/dev/shm` (shared memory virtual device) for veery specific scenario's like this though.

Regrading `/tmp` would be more appropriate solution but provided when there is no access to host environments (Kubernetes cluster or Underlying VMs where write access to host machines are not possible), `/dev/shm` makes better sense.

Anyway thanks for suggestion on this.

**Comment by makiika** [comment]
> read-only filesystem container.

I had the same issue but I fixed it by disabling the read-only file system in my container
