### ISSUE TITLE
How To Use: Without Dockerfile Not Working

### ISSUE THREAD

**Issue by bellds** [docker-library/httpd#17]
The How To Use the httpd Image gives the following command to run if a dockerfile is not used

> docker run -it --rm --name my-apache-app -v "$PWD":/usr/local/apache2/htdocs/ httpd

I believe this command is incorrect as I am not able to connect to port 80 if this is all I use.
However, when I run the following command I can connect to port 80 however, I always get a 404 error in my browser.

> docker run -it --rm --name my-apache-app -v "$PWD":/usr/local/apache2/htdocs/ -p 80:80 httpd

I am completely new to docker, but it feels to me that there are two issues:

1. The How To Use document has an error
2. The image also does not really have a volume at the described location.

Attaching a screening shot to assist in seeing what I did.
![docker-httpd-screenshot](https://cloud.githubusercontent.com/assets/18038605/14000177/01a83396-f10e-11e5-96aa-8b2f0c43ac82.jpg)

**Comment by bellds** [comment]
I discovered that the reason the -v argument was not working for me was because my working directory (e.g. the $PWD) was not under the C:\Users directory and it is a known limitation of docker.

I still believe the -p argument is required though.

**Comment by boxxxie** [comment]
enabling the ports is required.
also there is a hidden file that is required that should be in your root dir by the name of "http-foreground"
there is no mention of this required (executable) file in the documentation.

**Comment by yosifkit** [comment]
Forwarding ports is only necessary when you want access to the container from outside the docker host.  Currently, with `boot2docker` and `docker-machine` on Windows and OSX, this means that you always need a `-p` if you want to access it from Windows or OSX.  On Linux machines you can just hit the IP address of the container at the correct port.  This is applicable to all images generally and not really unique to the httpd image.
