### ISSUE TITLE
UTF-8 by default.

### ISSUE THREAD

**Issue by jtagcat** [docker-library/httpd#171]
I petition to add `AddDefaultCharset UTF-8` to the default configuration. Any thoughts?

**Comment by tianon** [comment]
Besides the adjustment of logs to stdout/stderr (per containerization norms), our default configuration is the default configuration provided by the upstream `httpd` project with no other modification/addition:

https://github.com/docker-library/httpd/blob/077141ee37fca63972292c562ec0f632d0f831b1/2.4/Dockerfile#L199-L205

I would suggest that if this makes sense as a default that it should probably be proposed to the upstream httpd project directly.
