### ISSUE TITLE
Failed build on Ubuntu 18

### ISSUE THREAD

**Issue by redskate** [docker-library/httpd#178]
The command

docker build -t my-apache2 .

for version 2.4 (copied the Dockerfile)

breaked with following problem:

Step 12/14 : COPY httpd-foreground /usr/local/bin/
COPY failed: file not found in build context or excluded by .dockerignore: stat httpd-foreground: file does not exist

How shell I proceed from here on?

**Comment by bendem** [comment]
Well, you can't just copy the dockerfile and ignore the backing files it requires, the `httpd-foreground` is [here](https://github.com/docker-library/httpd/blob/master/2.4/httpd-foreground).

**Comment by yosifkit** [comment]
> Well, you can't just copy the dockerfile and ignore the backing files it requires, the `httpd-foreground` file is [here](https://github.com/docker-library/httpd/blob/master/2.4/httpd-foreground).

And if you are just downloading from the browser, don't forget to `chmod +x` it. (or just git clone the repo and the execute permissions will be correct).
