### ISSUE TITLE
libaprutil1-ldap is missing for LDAP authentication support

### ISSUE THREAD

**Issue by mcallaway** [docker-library/httpd#18]
With a custom httpd.conf, provide a Location or Directory that requires Basic Auth provided by ldap. Start a container with the httpd image in debug mode and see:

apache_1   | [Wed Mar 30 19:12:33.430159 2016] [ldap:info] [pid 1:tid 140285203179392] AH01320: LDAP: SSL support unavai
lable
apache_1   | ldap_url_parse_ext(ldap://localhost/)
apache_1   | ldap_init: trying /etc/ldap/ldap.conf
apache_1   | ldap_init: using /etc/ldap/ldap.conf
apache_1   | ldap_init: HOME env is /root
apache_1   | ldap_init: trying /root/ldaprc
apache_1   | ldap_init: trying /root/.ldaprc
apache_1   | ldap_init: trying ldaprc
apache_1   | ldap_init: LDAPCONF env is NULL
apache_1   | ldap_init: LDAPRC env is NULL

Then make a request and see:

apache_1   | ldap_err2string

Strace the process and see:

13364 open("/usr/lib/x86_64-linux-gnu/apr-util-1/apr_ldap-1.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

That library is provided by the libaprutil1-ldap package.

**Comment by mcallaway** [comment]
This works:

    diff --git a/2.4/Dockerfile b/2.4/Dockerfile
    index 2dd7a20..dddc2b2 100644
    --- a/2.4/Dockerfile
    +++ b/2.4/Dockerfile
    @@ -15,6 +15,7 @@ RUN apt-get update \
            && apt-get install -y --no-install-recommends \
                    libapr1 \
                    libaprutil1 \
    +               libaprutil1-ldap \
                    libapr1-dev \
                    libaprutil1-dev \
                    libpcre++0 \

**Comment by yosifkit** [comment]
:+1: Seems fine to me; want to make a PR?

**Comment by mcallaway** [comment]
https://github.com/docker-library/httpd/pull/19

**Comment by mcallaway** [comment]
The PR fails Travis CI tests on what appears to be a transient failure of apt-get update to update the apt cache.

**Comment by yosifkit** [comment]
:heart:
