### ISSUE TITLE
why version was downgraded ?

### ISSUE THREAD

**Issue by sielaq** [docker-library/httpd#180]
Hi fellows,

is there any reason (security?) why version was downgraded with last commit ?

**Comment by tianon** [comment]
See https://lists.apache.org/x/thread.html/r8dd2f0e15010650db81ffa34dfc3f4d1d46e5fde1fb82509b0379257@%3Cdev.httpd.apache.org%3E:

> Hi all,
> 
> as you probably have noticed, the 2.4.47 has been distributed on mirrors
> but not announced, neither on your favorite ML, nor on the official
> httpd.apache.org website.
> 
> The reason is a very last minute regression discovered a few hours
> before the announcement.
> 
> So, as the 2.4.32 release in March 2018, this 2.4.47 release will never
> be officially announced.
> 
> 
> In the hope of this issue being solved in the meantime, I plan a new T&R
> on Sunday May 16, 2021, forecasting for a 2.4.48 release on Sunday May
> 23 or Monday May 24.
> 
> 
> Best regards,
> Christophe JAILLET

So our automation frankly jumped the gun a little bit in publishing it. On that same mailing list, there's a vote thread for a new release in progress (https://lists.apache.org/x/thread.html/r299eee4dc3ede28b9edcac4248380ae0d52cf1f37e79ab4a301d4e10@%3Cdev.httpd.apache.org%3E).

**Comment by sielaq** [comment]
thanks
