### ISSUE TITLE
httpd with alpine 3.13 tag

### ISSUE THREAD

**Issue by csandanov** [docker-library/httpd#185]
The latest httpd version with Alpine 3.14 has issues running on old versions of Docker due to https://github.com/alpinelinux/docker-alpine/issues/182. Is there a way we can tag the old version with alpine 3.13 tag?

**Comment by csandanov** [comment]
Maybe I should've posted it to https://github.com/docker-library/official-images because it also concerns other images (memcached, postgres). Some images like php and redis already have alpine version tag.

**Comment by tianon** [comment]
Ah good call -- this is definitely the appropriate place to file and track this (and a separate issue for any other affected repo where we didn't already have the "escape hatch" aliases).  I'll get a PR up shortly. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/10510 :+1:

**Comment by csandanov** [comment]
Thank you! 

As I understand Alpine 3.14 makes all alpine-based images unusable in certain use cases if you're using Docker prior to 20.10.0 which was released on Dec 8th 2020 (not that long ago when dealing with infrastructure). As an example I just spun up a simple Debian 9 VM on DigitalOcean and installed docker according to Docker's official documentation – and I have Docker 19.03.15. Could this be a consideration of keeping the 3.13 variant for a while?

**Comment by Hello71** [comment]
if you read the release note on this issue which I spent hours researching and documenting, Docker 20.10.0 is only one of three options available to fix the issue. runc v1.0.0-rc93 is another option, which, as has been documented since the Alpine Linux 3.14 release, is part of containerd.io 1.4.3-2, which was added to Docker's Debian repositories on March 3, over five months ago.

**Comment by Hello71** [comment]
also, while not strictly related to this issue, Debian 10 was released over 2 years ago, and Docker 19.03 is EOL.
