### ISSUE TITLE
WebDAV broken since Alpine 3.13

### ISSUE THREAD

**Issue by timschumi** [docker-library/httpd#201]
WebDAV requires a locking database, which gets created using the database driver previously known as `apr-util-dbm_db`. However, this package got removed by the Alpine developers and is neither included nor installable on any Alpine 3.13 based images or newer.

This results in a slightly confusing error message when trying to set up a WebDAV server using that image:

```
(20019)DSO load failed: AH00576: The DBM driver could not be loaded
The locks could not be queried for verification against a possible "If:" header.  [500, #0]
Could not open the lock database.  [500, #400]
(20019)DSO load failed: [client 172.21.0.7:37564] Could not open property database.  [500, #1]
```

As outlined in [the Pull Request where the Alpine version was bumped to 3.13](https://github.com/docker-library/httpd/pull/173#discussion_r571306320), Alpine switched to the `ndbm` database backend, which does not require this specific driver. Please consider making a similiar change to the Apache server that is built as a part of the `alpine` images to avoid relying on the missing driver.

**Comment by timschumi** [comment]
I now set up a slightly stripped down sample config that will reproduce the issue when queried using `curl -X PUT http://localhost:8080/test` (the error message mentioned above will show up in stdout/`docker-compose logs`):

<details>
<summary>docker-compose.yml</summary>

```
version: "3.6"

services:
  webdav:
    image: docker.io/httpd:alpine
    ports:
      - 8080:80
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
```
</details>

<details>
<summary>httpd.conf</summary>

```
ServerRoot "/usr/local/apache2"

Listen 80

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule filter_module modules/mod_filter.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule version_module modules/mod_version.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dav_module modules/mod_dav.so
LoadModule status_module modules/mod_status.so
LoadModule dav_fs_module modules/mod_dav_fs.so
LoadModule dav_lock_module modules/mod_dav_lock.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so

<IfModule unixd_module>
User daemon
Group daemon
</IfModule>

ServerAdmin you@example.com

<Directory />
    AllowOverride none
    Require all denied
</Directory>

DAVLockDB "/tmp/DavLockDB"
DocumentRoot "/usr/local/apache2/htdocs"
<Directory "/usr/local/apache2/htdocs">
    DAV on
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>

ErrorLog /proc/self/fd/2
LogLevel warn

<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common

    <IfModule logio_module>
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>

    CustomLog /proc/self/fd/1 common
</IfModule>

<IfModule mime_module>
    TypesConfig conf/mime.types

    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
</IfModule>
```
</details>

Switching `docker.io/httpd:alpine` for `docker.io/httpd:latest` successfully mitigates the database error, the new "permission denied" error is just happening because the server doesn't have permission to write into htdocs, but that is expected.

**Comment by tianon** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/12534 makes it sound like this might be expected :weary:

**Comment by timschumi** [comment]
The fact that `dbm_db` has been removed is expected, but from what I grasped of the discussion in the Alpine 3.13 bump the idea was that a different DB backend got selected as default...

Maybe it's time to build apr as well instead of relying on the Alpine prebuilt?

**Comment by tianon** [comment]
So I guess we should probably close this, right? (Since there's not really something we can/would do to fix it? :see_no_evil:)

**Comment by timschumi** [comment]
I guess so, unless we want to dive into building the package ourselves (but I don't think that we want to).

**Comment by tianon** [comment]
Yeah, unfortunately agreed; thanks :heart:

**Comment by neingeist** [comment]
This is unfortunately still a problem with httpd:2.4-alpine. Going to have to switch to the `2.4-bullseye` image.

**Comment by KEMBL** [comment]
@neingeist 
httpd:2.4.54-bullseye  gives me the same:

```
BDB0004 fop_read_meta: /var/lib/dav/DavLock: unexpected file type or format
BDB0004 fop_read_meta: /var/lib/dav/DavLock: unexpected file type or format
[dav:error] [pid 177:tid 140348097545984] [client 10.0.8.21:35442] The locks could not be queried for verification against a possible "If:" header.  [500, #0]
[dav:error] [pid 177:tid 140348097545984] [client 10.0.8.21:35442] Could not open the lock database.  [500, #400]
[dav:error] [pid 177:tid 140348097545984] (120013)APR does not understand this error code: [client 10.0.8.21:35442] Could not open property database.  [500, #1]
```

**Comment by neingeist** [comment]
> @neingeist httpd:2.4.54-bullseye gives me the same:
> 
> ```
> BDB0004 fop_read_meta: /var/lib/dav/DavLock: unexpected file type or format
> BDB0004 fop_read_meta: /var/lib/dav/DavLock: unexpected file type or format
> [dav:error] The locks could not be queried for verification against a possible "If:" header.  [500, #0]
> [dav:error] Could not open the lock database.  [500, #400]
> [dav:error] (120013)APR does not understand this error code: Could not open property database.  [500, #1]
> ```

Hmm. I'm now running an image based on httpd:2.4-bullseye without this issue. My config contains this, however:
~~~
DavLockDB "/usr/local/apache2/var/DavLock"
~~~

**Comment by timschumi** [comment]
> Hmm. I'm now running an image based on httpd:2.4-bullseye without this issue.

Not surprising, since that is not an Alpine-based image. Debian still ships BerkeleyDB, so they don't experience the database issues that are the topic of this issue.

**Comment by elehcim** [comment]
Is there a workaround to fix this?

**Comment by timschumi** [comment]
> Still a problem here with the latest bookworm image ([2.4.58-bookworm](https://hub.docker.com/layers/library/httpd/2.4.58-bookworm/images/sha256-d70861224a52d0175c4b485ef7b70f56125f2c74d8a489a9a8ca10e3656929c9?context=explore))

If it's not an Alpine image, it's not this issue.
