### ISSUE TITLE
Environment variable in httpd-foreground

### ISSUE THREAD

**Issue by patricknazar** [docker-library/httpd#21]
Hi there

I'm new to docker so forgive me if this makes no sense. I'm just curious. Shouldn't the httpd-foreground script not have a hardcoded path to the pid file it's trying to remove but instead use the environment variable HTTPD_PREFIX? I imagine it doesn't make a difference here but I'm just trying to comprehend the docker philosophy.

Cheers

**Comment by yosifkit** [comment]
No specific reason that I can think of; probably was not thinking about the env when the foreground script was written.

**Comment by tianon** [comment]
IIRC, the path to that particular file is hard-coded in the default config
(not using an environment variable).
