### ISSUE TITLE
mod_rewrite doesn't work on arm64

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [docker-library/httpd#222]
Dockerfile:

```dockerfile
FROM httpd:2.4.54
RUN sed -i -e 's/^#\(LoadModule .*mod_rewrite.so\)/\1/' conf/httpd.conf
```

It works on amd64, but doesn't work on arm64.
Error: exec /usr/local/bin/httpd-foreground: exec format error

**Comment by tianon** [comment]
With your exact `Dockerfile` and `--platform linux/arm64/v8`, I'm unable to reproduce. :confused: :disappointed:

**Comment by dzmitry-rudnouski** [comment]
Thank you, let me try.
