### ISSUE TITLE
HTTPS/SSL no longer working in 2.4.57

### ISSUE THREAD

**Issue by FlorianK84** [docker-library/httpd#237]
Updated image to latest (2.4.57) last night, now HTTPS/SSL is no longer working. Getting an error:

> Cannot load modules/mod_ssl.so into server: libssl.so.1.1: cannot open shared object file: No such file or directory

modules/mod_ssl.so exists. Downgrading image to 2.4.56 works fine.

**Comment by bendem** [comment]
> libssl.so.1.1: cannot open shared object file: No such file or directory

The file it's complaining about is libssl.so.1.1, not mod_ssl.so.

Can you provide the sha256 of the image you're using because the latest doesn't link against libssl1.1 but libssl3:

```
root@0316968ad584:/usr/local/apache2# ldd modules/mod_ssl.so
        linux-vdso.so.1 (0x00007ffc31d7e000)
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007fb41599c000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007fb41551b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb41533a000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb415a8a000)
```

**Comment by FlorianK84** [comment]
Ah... Based on your information I found the problem... How embarrassing! I didn't see that there is a volume misconfiguration. The whole directory /usr/local/apache2 is mounted as volume and contains the old libs. I changed the volume config and now everything is working just fine. Thx for your help!
