### ISSUE TITLE
file not found in build context or excluded by .dockerignore: stat httpd-foreground: file does not exist

### ISSUE THREAD

**Issue by glasswingprince** [docker-library/httpd#239]
in the DockerFile, line no 12,
COPY httpd-foreground /usr/local/bin/

**Comment by glasswingprince** [comment]
Hello Team,

I have cloned.. but still getting the same error.


Regards
Prince
________________________________

**Comment by tianon** [comment]
I'm sorry, but without more information we won't be able to help. :sweat_smile:

I'm not able to reproduce with either of `docker build 'https://github.com/docker-library/httpd.git#:2.4'` or `git clone https://github.com/docker-library/httpd.git && docker build httpd/2.4` :see_no_evil:

**Comment by CapedBojji** [comment]
This is still an issue, when doing FROM httpd:latest it produces that error

**Comment by LaurentGoderre** [comment]
Are you sure you are building in the right context (i.e. not building using the `f` flag and being in the wrong folder)?

**Comment by CapedBojji** [comment]
> Are you sure you are building in the right context (i.e. not building using the `f` flag and being in the wrong folder)?

you are right. In my docker compose I had set the context to the directory where the docker file was located. but after removing that and just setting the dockerfile field to exactly where it is relative to the compose.yaml it worked. Btw what exactly is the context meant for?

**Comment by LaurentGoderre** [comment]
@CapedBojji the context is the directory that gets sent to the build. When building an image you can't include files that aren't in that context (like from your user's Download directory for example). The context is also used to determine what changed and if a cached layer can be used instead of rebuilding it
