### ISSUE TITLE
Httpd error:httpd.conf: Invalid LoadModule path D:/\xc8\xed

### ISSUE THREAD

**Issue by Aaron-PanJi** [docker-library/httpd#241]
### CurrentBehavior
After installing wampserver, the chart will continue to display red after startup and cannot be started. Then, follow the method on Baidu to open a command prompt line in the corresponding folder, and run the httpd command with an error
<img width="416" alt="image" src="https://github.com/docker-library/httpd/assets/120549770/6f479b0d-d04b-4b68-b3c8-e23b915f5a9e">
### ExpectedBehavior
Wampserver can be used normally

**Comment by thesuperzapper** [comment]
To the maintainers of this repo, this account is a bot, I have reported them to github, but it's very strange.

It seems to copy people's issues from other places and post them.

**Comment by tianon** [comment]
:disappointed: thanks for the heads up :heart:
