### ISSUE TITLE
Update image to 2.4.58

### ISSUE THREAD

**Issue by logopk** [docker-library/httpd#242]
Please update the image as there are Security Fixes in the lates release

https://downloads.apache.org/httpd/CHANGES_2.4.58

Thank you.

Peter

**Comment by yosifkit** [comment]
> https://github.com/docker-library/httpd/tree/338f9a4b1e36e09ad2733f36f19e31157f5c959c#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet

It's in process: https://github.com/docker-library/official-images/pull/15586
