### ISSUE TITLE
I18n support in mod_proxy_html requires mod_xml2enc

### ISSUE THREAD

**Issue by sebix** [docker-library/httpd#256]
Using httpd:2.4.58-bookworm as reverse proxy gives this warning message in the error log:
```
[Mon Feb 26 16:08:35.768182 2024] [proxy_html:notice] [pid 1583:tid 140355496699776] AH01425: I18n support in mod_proxy_html requires mod_xml2enc. Without it, non-ASCII characters in proxied pages are likely to display incorrectly.
```
The Dockerfile already mentions this library:
https://github.com/docker-library/httpd/blob/26548a4129140d99916084ff5babe42dcc7cb88a/2.4/Dockerfile#L34
But it seems, `mod_xml2enc` is not active or available.

**Comment by LaurentGoderre** [comment]
mod_xml2enc definitely are there

```
find . | grep 'mod_xml2enc'
./modules/mod_xml2enc.so
./include/mod_xml2enc.h
```

**Comment by sebix** [comment]
You are entirely right; this is wholly a user error. The module needs to be loaded, that's all.
