### ISSUE TITLE
[Question] How to install httpd modules without load errors due to apt package incompatibilities?

### ISSUE THREAD

**Issue by samueldc** [docker-library/httpd#265]
[Question] How to install httpd modules without load errors due to apt package incompatibilities?

Hi everyone,

I'm trying to install some modules using apt (e.g.: libapache2-mod-perl2). However, apt doesn't recognize that httpd is already present and will attempt to install apache2-bin as a dependency. The version of the apache2-bin package installed by apt might not be compatible with the httpd version currently in use, which is exactly my case.

For example, I'm using the httpd:2.4-bullseye image, and when installing libapache2-mod-perl2 apt installs apache2-bin package version 2.4.61. This version is incompatible with the other manually installed bynaries. As a result, when trying to load certain modules, such as mod_mime, I receive the following error:

```
Syntax error on line 124 of /usr/local/apache2/conf/httpd.conf: Cannot load modules/mod_mime.so into server: /usr/local/apache2/modules/mod_mime.so: undefined symbol: ap_set_content_type_ex
```

I've managed to install apache2-bin version 2.4.59 through apt, which seems compatible with the image installation, but I can't rely on that forever.

My Dockerfile:

```
FROM httpd:2.4-bullseye
    RUN ln -s /usr/local/apache2 /usr/lib/apache2
    RUN apt-get update \ 
        && apt-get install -y --no-install-recommends locales \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* \
        && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
    ENV LANG=en_US.utf8
    RUN apt-get update \ 
        && apt-get install -y --no-install-recommends apache2-bin=2.4.59-1~deb11u1 \ 
        perl libapache2-mod-perl2 \
        libwww-perl s3cmd \
        && apt-get clean
```

Any thoughts about that?

Best regards!

samueldc

**Comment by samueldc** [comment]
Another solution is removing the symbolic link of the server root path (removing line `RUN ln -s /usr/local/apache2 /usr/lib/apache2` from the dockerfile above) and load the module referencing the full path (e.g.: `LoadModule perl_module /usr/lib/apache2/modules/mod_perl.so` instead of `LoadModule perl_module modules/mod_perl.so`). That way httpd looks to work just fine.

But I'm still concerned with compatibilities problems between the bynaries of the manual installation and the ones installed by apt.

**Comment by samueldc** [comment]
More about it from the Check_MK forum. Looks like more people are struggling with this matter:

https://forum.checkmk.com/t/apache-failed-with-syntax-error/48244

**Comment by tianon** [comment]
Unfortunately, this image installs `httpd` in the "upstream recommended" / documented way, namely building it from source.  If you want more modules for it, and you want them to be compatible with it, you'll likely need to build them from source also.  I would _not_ recommend mixing-and-matching in the way you've described with package-built binaries/modules and this image.  For that, you're going to be _much_ better off just installing `httpd` itself from Debian/packages as well, and not using this image at all.

**Comment by samueldc** [comment]
Totally agree with you. The problem is installing httpd from a base debian image is very troublesome and we are forced to use a process like supervisord since installing httpd from apt doesn't provide a httpd command like httpd-foreground.

**Comment by tianon** [comment]
Oh, it's uh, not much: :sweat_smile:

https://github.com/docker-library/httpd/blob/3056c115a9f3c2467cc6f67470cfded70c4adc64/2.4/httpd-foreground#L7

See also the "apache" variants of https://hub.docker.com/_/php which do exactly that:

https://github.com/docker-library/php/blob/21e6a92a1998c7f3157bc5df291fbd600330e33d/8.3/bookworm/apache/Dockerfile#L286

https://github.com/docker-library/php/blob/21e6a92a1998c7f3157bc5df291fbd600330e33d/8.3/bookworm/apache/apache2-foreground#L40

All that "envvars" and directory logic can be avoided via some other wrapper, but I can't remember it offhand (apache2ctl maybe?); this is what we do to prep for all that, if you _do_ want that behavior:

https://github.com/docker-library/php/blob/21e6a92a1998c7f3157bc5df291fbd600330e33d/8.3/bookworm/apache/Dockerfile#L54-L90

**Comment by tianon** [comment]
Confirmed, the following seems to work pretty reasonably:

```dockerfile
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends apache2 && rm -rf /var/lib/apt/lists/*

CMD ["apache2ctl", "-DFOREGROUND"]
```

Built, ran, connected via my browser on port 80, got:

![image](https://github.com/user-attachments/assets/b806d3d5-5ad3-45ed-8357-d23a9ce30139)

**Comment by tianon** [comment]
Notably, you might want to include `--init`/`init: true` (or install/use `tini` explicitly) since `apache2ctl` is a shell script that notably does _not_ use `exec` when launching the httpd process (https://salsa.debian.org/apache-team/apache2/-/blob/1d2fb82219a579e603dd8c52f3cccb0752f06115/debian/apache2ctl#L212), so will not transmit signals correctly by default (which I think is why we ended up implementing so much logic ourselves over in PHP).

**Comment by samueldc** [comment]
@tianon Thank you so much for the help. I'll try that right away.
