### ISSUE TITLE
Build Timestamp

### ISSUE THREAD

**Issue by Virsacer** [docker-library/httpd#266]
Hi,
I pulled the new image

![image](https://github.com/user-attachments/assets/f8f91ec3-d39d-4d9b-8432-e6893dd4833d)

but Docker inspect shows, that this image is almost 2 month old:

```
root@DOCKER ~ $ docker inspect httpd:2.4-alpine | grep -E 'httpd@sha256|Created'
            "httpd@sha256:1126743b13846fe049683762a8fccfbd4a3966040eb5ff38c785eceebf0fcce6"
        "Created": "2024-07-17T23:31:14Z",
root@DOCKER ~ $
```

**Comment by tianon** [comment]
We set [`SOURCE_DATE_EPOCH`](https://reproducible-builds.org/docs/source-date-epoch/) ([buildkit docs](https://github.com/moby/buildkit/blob/436609d8057cecf90628091b68e3bc3bd7e01f1d/docs/build-repro.md#source_date_epoch)) while building -- if you want to see the date the build was performed, you'll want to look at the `org.opencontainers.image.created` annotation we add in the image index ([relevant code](https://github.com/docker-library/meta-scripts/blob/3cec72f5016e237335694ca9e307b7e24b073e61/meta.jq#L170)) instead: https://oci.dag.dev/?image=httpd:2.4-alpine (`"org.opencontainers.image.created": "2024-09-06T23:20:57Z"`).

**Comment by Virsacer** [comment]
Thanks for the explanation
I was confused by the fact, that `docker images` listed both the freshly downloaded and the previous image with CREATED "7 weeks ago"

**Comment by tianon** [comment]
Indeed, it's unfortunate -- I wish we could somehow have Docker show when we built it _and_ still have the possibility of a reproducible build in the future. :disappointed:

Glad that answers your question!
