### ISSUE TITLE
how to start image in docker?

### ISSUE THREAD

**Issue by arjanpetersen** [docker-library/httpd#29]
Hi,

I have built a dockerfile from the directory "2.4". I did copy the file to my ubuntu OS, and ran following commands:

$ docker build -t my-apache2 .
$ docker run -it --rm --name my-running-app my-apache2

The first command seems to works. It took quite a while but then it finished. But running the image is not possible. Im getting the following error response:

docker: Error response from daemon: Container command 'httpd-foreground' not found or does not exist..

Any idea what this could be? Or am I following the wrong path? (im a docker newbie!)

thanks.

Arjan

**Comment by yosifkit** [comment]
You probably need to `chmod +x httpd-foreground` in the `2.4` directory and `docker build` again.

**Comment by jburtondev** [comment]
@arjanpetersen have you tried the suggestion from @yosifkit? I am thinking that this needs to be closed now.

**Comment by tianon** [comment]
Agreed, this is solved (we cannot reproduce a failure). :+1:
