### ISSUE TITLE
DNS lookup failure when used with docker-compose

### ISSUE THREAD

**Issue by rodlogic** [docker-library/httpd#31]
I have been seeing the following when using httpd to front other docker services using docker-compose:
```
p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/services/testyanf">GET&nbsp;/services/testyanf</a></em>.<p>
Reason: <strong>DNS lookup failure for: services-service</strong></p></p>
```

From the container I can ping the services-service fine, but httpd doesn't seem to be able to resolve it. I also checked that /etc/hosts does have the services-service defined.

**Comment by charleshuber** [comment]
I have the same problem. Did you find a solution ?

**Comment by perwramdemark** [comment]
Got the same issue running mod_procy in the httpd:2.4 docker image
