### ISSUE TITLE
mod_http2 not included

### ISSUE THREAD

**Issue by janweinschenker** [docker-library/httpd#33]
Hi all,

could you please add mod_http2 to your image?

Thanks and best regards
Jan

**Comment by yosifkit** [comment]
Looks like we need a newer `nghttp2`:
```
checking whether to enable mod_http2... configure: WARNING: nghttp2 version is too old
no (disabled)
```

We will probably have to pull it from `sid`: https://packages.debian.org/sid/nghttp2.  I'll start a PR for it. :smile:

**Comment by janweinschenker** [comment]
That's great. Thank you!!!
