### ISSUE TITLE
apxs does not work

### ISSUE THREAD

**Issue by rafaelsierra** [docker-library/httpd#37]
# Steps to reproduce

```
$ docker run --rm -it httpd:2.4 bash
root@0907b0eb89fd:/usr/local/apache2# apxs
cannot open /usr/local/apache2/build/config_vars.mk: No such file or directory at /usr/local/apache2/bin/apxs line 203.
```

# Expected behavior

I should be able to use apxs to build modules during build time (e.g.: from a Dockerfile)

# Extra background
I have an image that uses XSendFile, and I need to build it during `docker build` but with current `httpd:2.4`, I can't.

I was using a cached version from months ago, so I am not sure when this was introduced, but seems that c8e349af4adcd2 is related

**Comment by yosifkit** [comment]
Looks like it was https://github.com/docker-library/httpd/pull/35; apparently `build` is not useless.
