### ISSUE TITLE
How to add mod_perl

### ISSUE THREAD

**Issue by javathought** [docker-library/httpd#4]
the module perl is not included in this image. How can I add the module to this image ?

**Comment by tianon** [comment]
I guess it depends on how `mod_perl` would be included in a normal from-source install of Apache.  Does this image include the development headers and utilities necessary for building `mod_perl` appropriately?

https://perl.apache.org/docs/2.0/user/install/install.html#Installing_mod_perl_from_Source seems like a good place to start digging.

**Comment by cellpjs** [comment]
I don't know about mod_perl but mod_proxy is included in src/httpd/modules but not in this image (since you do 'rm src/httpd'). You are supposed be able to compile and install modules using apxs.

**Comment by palfrey** [comment]
Seeing similar issues with mod_wsgi I suspect. I think part of it is the following problem

```
root@0a0897fbf60d:/usr/local/apache2# apxs -q APR_CONFIG
/usr/bin/apr-1-config
apxs:Error: /usr/bin/apr-1-config not found!.
```

Something is definitely not right with the apxs config

**Comment by palfrey** [comment]
Hmm. Turns out my apxs issue was a lack of `libapr1-dev`. Installed that and the problem went away. This image may want to consider not uninstalling that when doing the cleanup.

**Comment by yosifkit** [comment]
Whoops, I guess we are too aggressive on removing build dependencies; care to make a PR to keep that installed?

**Comment by palfrey** [comment]
@yosifkit See #7

**Comment by palfrey** [comment]
Just out of curiosity (no, I'm not maintaining this, but feel free to use as a base) I tried building mod_perl after my fixes from #7 and it looks good. See below for example Dockerfile 

```
FROM httpd/2.4.17
ADD http://www.eu.apache.org/dist/perl/mod_perl-2.0.9.tar.gz mod_perl-2.0.9.tar.gz
RUN tar -zxvf mod_perl-2.0.9.tar.gz
RUN apt-get update
RUN apt-get install -y libfile-spec-native-perl make gcc libperl-dev
RUN cd mod_perl-2.0.9 && perl Makefile.PL MP_APXS=/usr/local/apache2/bin/apxs && make install
```

**Comment by tianon** [comment]
Woot, #7 was merged, so `mod_perl` should be properly buildable. :smile: :+1: :innocent:

**Comment by prashanthmadi** [comment]
Hi @palfrey 

I tried creating a container using your code but it fails with below error
```
Makefile:102: recipe for target 'install' failed

[91mmake[1]: *** [install] Error 1
[0m
make[1]: Leaving directory '/usr/local/apache2/mod_perl-2.0.10/src/modules/perl'

Makefile:512: recipe for target 'modperl_lib_install' failed
```
https://hub.docker.com/r/prashanthmadi/appserviceperl/builds/bpvmzclw29gektpvb2wa6xn/

I'm not totally into perl.. might be simple fix.. can you help :)

**Comment by palfrey** [comment]
@prashanthmadi Not a clue TBH. Also not a Perl person.

**Comment by sbrewin** [comment]
@prashanthmadi 
Try piping the output of make to a file:
`RUN cd mod_perl-2.0.10 && perl Makefile.PL MP_APXS=/usr/local/apache2/bin/apxs && make install > make.log`
Also, ensure libgdbm.so is available with:
`ln -s /usr/lib/x86_64-linux-gnu/libgdbm.so.3.0.0 /usr/lib/libgdbm.so`

**Comment by prashanthmadi** [comment]
thanks @sbrewin 

I was able to create perl sample web app using another approach.
https://github.com/prashanthmadi/appserviceperl

**Comment by sbrewin** [comment]
@prashanthmadi 
Ok. For completeness to install mod_perl using the following must be installed...

```
# Add mod_perl build dependencies
RUN set -x \
    && apt-get update \
    && apt-get install -y libfile-spec-native-perl make gcc libperl-dev
```
...then compile and install mod_perl with...

```
#  Fetch mod_perl source, build and install it
#  Note: The fetch URL should be adjusted to point to a local mirror
ADD http://www.eu.apache.org/dist/perl/mod_perl-2.0.10.tar.gz mod_perl-2.0.10.tar.gz
RUN set -x \
    && ln -s /usr/lib/x86_64-linux-gnu/libgdbm.so.3.0.0 /usr/lib/libgdbm.so \
    && tar -zxvf mod_perl-2.0.10.tar.gz \
    && rm mod_perl-2.0.10.tar.gz \
    && cd mod_perl-2.0.10 \
    && perl Makefile.PL MP_AP_PREFIX=/usr/local/apache2 \
    && make \ 
    && make install
```

... and finally clean up with...

```
# Remove mod_perl build dependencies
RUN set -x \
    && rm -r mod_perl-2.0.10  \
    && apt-get purge -y --auto-remove make gcc libperl-dev \
    && rm -rf /var/lib/apt/lists/*
```
The principle difference to the original is the explicit invocation of `make` to compile mod_perl prior to installing it with `make install`.

Good luck.
Steve
