### ISSUE TITLE
Switching from OpenSSL to LibreSSL causes some CA certs to be rejected

### ISSUE THREAD

**Issue by kgilden** [docker-library/httpd#44]
Hi! Using the latest version of this image - `httpd:2.4.25-alpine` - and possibly earlier ones prevents some non-conforming CA certificates from being used. I tested with `httpd:2.4.25` and its fine there.

Estonian Certification Center's [root CA](https://sk.ee/upload/files/EE_Certification_Centre_Root_CA.pem.crt) is not conforming to Section [4.1.2.5 of RFC5280](https://tools.ietf.org/html/rfc5280#section-4.1.2.5) and is using `GeneralizedTime` instead of `UTCTime` for validity dates before 2050. LibreSSL is more strict than OpenSSL in following this section. As a consequence no server nor client certificates descending from such faulty certificates can be used together with this container. There's also [an e-mail](http://webcache.googleusercontent.com/search?q=cache:xFIt1kezRaQJ:permalink.gmane.org/gmane.comp.encryption.libressl/281+&cd=3&hl=en&ct=clnk&gl=us) about the same problem in some random mailing list.

The impact is that this image cannot be used for building services for Estonian citizens nor its e-residents as client authentication is widely used here and the faulty cert is at the root of all these certs. And if there is at least one such faulty root CA, there's likely others, because I'm sure the CA guys used some software to generate the cert.

Would it be possible to somehow allow switching OpenSSL vs LibreSSL? Perhaps separate tags? In an ideal world I'd vouch for LibreSSL, but reality is different.

The problem was introduced in b95f1aba with the switch from `openssl` to `libressl`.

**Comment by yosifkit** [comment]
Unfortunately moving back would make us lose `mod_session_crypto`; the Debian based image still uses OpenSSL in the `httpd:2.4` image, so it should be able to work.

**Comment by tianon** [comment]
Closing since this is the unfortunate reality of where we're at today, and not something we're likely to change.
