### ISSUE TITLE
Add the ability to launch by root

### ISSUE THREAD

**Issue by duhon** [docker-library/httpd#48]
Please add "EXTRA_CFLAGS=-DBIG_SECURITY_HOLE" before compiling. Run as root justified for docker container

**Comment by yosifkit** [comment]
The container does start as root so it can open privileged ports and then apache drops down to the user specified.  What is the use case that needs the apache process to stay as the root user?

**Comment by duhon** [comment]
Child processes run on behalf of "daemon", because in the config specified 
```
<IfModule unixd_module>
    User daemon
    Group daemon
</IfModule>
```
If you change the above setting to 'User root' you'll get an error. This processes are processes are used when working with external folder (volumes from docker-compose)

**Comment by tianon** [comment]
Sorry for the long tail here.

I'm still very, very wary of enabling this.  Upstream calls it "BIG_SECURITY_HOLE", and they have some pretty solid reasons for doing so.  I agree that running as root inside a container is _less bad_ than running as root on the host, but it's still not a _great_ plan.

**Comment by tianon** [comment]
Closing given that this is something upstream actively discourages (to the point of forcing users to *recompile* `httpd` to enable it), so it isn't something we're going to enable.
