### ISSUE TITLE
about enabling ssl

### ISSUE THREAD

**Issue by shawhu** [docker-library/httpd#49]
following the README.md on the main page, I was trying to enable the ssl support.
and I found that I couldn't start the container every time I enabled ssl in the httpd.conf. 

I'm new to the docker community and only recently been using it so as far as I can tell, it could/probably be my own problem that I must have missed some obvious steps in between...

Here is what I've done and tried.
my dockerfile

    FROM httpd:latest
    COPY ./public-html/ /usr/local/apache2/htdocs/
    COPY ./sslkeys/ /usr/local/apache2/conf/
    COPY httpd.conf /usr/local/apache2/conf/
    COPY httpd-ssl.conf /usr/local/apache2/conf/extra/

my sslkeys folder has all the key files
![screen shot 2017-04-28 at 11 45 15 am](https://cloud.githubusercontent.com/assets/1240808/25513513/2b3c6d68-2c08-11e7-9a3a-b48ca5f785d5.png)

lines in my httpd.conf

    # Secure (SSL/TLS) connections
    Include conf/extra/httpd-ssl.conf  

lines in my httpd-ssl.conf, the reason that I must change something in httpd-ssl.conf is that my ssl certificate provider geotrust and godaddy they all issue certificates with intermediate ca file. please see my changes of httpd-ssl.conf below for more detail

    SSLCACertificatePath "/usr/local/apache2/conf/ssl.crt"
    SSLCertificateChainFile "/usr/local/apache2/conf/server-ca.crt"

note: I've tried with both but only one at a time. I'm not sure which one should I enable. From godaddy's help page, https://www.godaddy.com/help/apache-install-a-certificate-centos-5238
![screen shot 2017-04-28 at 11 43 00 am](https://cloud.githubusercontent.com/assets/1240808/25513464/e31fb0b2-2c07-11e7-9918-c8f056f3cd95.png)
so you can see why I tried both. anyway, it doesn't work in both cases.

And, then, I build the image with no problem
and I run it with

    docker run -it --name httpd -p 8888:80 -p 8889:443 myimage

with error

    AH00526: Syntax error on line 174 of /usr/local/apache2/conf/extra/httpd-ssl.conf:
    SSLCACertificatePath: directory '/usr/local/apache2/conf/ssl.crt' does not exist

And the container can't start. the only option is to remove it.

I tried to disable Include conf/extra/httpd-ssl.conf in httpd.conf and build and run it, this time it run, and I tried to docker exec -it httpd /bin/bash and I found that all my key files are there. They do exist.
![screen shot 2017-04-28 at 11 52 42 am](https://cloud.githubusercontent.com/assets/1240808/25513640/40adec98-2c09-11e7-9cf1-95d5102cc439.png)

I've also enabled a couple mods in httpd.conf as well, for example the ssl mod is not enabled by default and I recalled there's more that I have enabled because I saw an error or two that asking me to. one is for enable a cache, another one is for url rewrite.

Please help, thanks!!

**Comment by dcolley** [comment]
did you find a solution? 
could it be due to file permissions? 
Under normal (non docker) operations apache will warn/error when the crt files have 777

**Comment by yosifkit** [comment]
`SSLCACertificatePath` needs to be a path to a folder, not to a specific file:

>This directive sets the directory where you keep the Certificates of Certification Authorities (CAs) whose clients you deal with. These are used to verify the client certificate on Client Authentication.
>
> The files in this directory have to be PEM-encoded and are accessed through hash filenames. So usually you can't just place the Certificate files there: you also have to create symbolic links named hash-value.N. And you should always make sure this directory contains the appropriate symbolic links.
>
> \- https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslcacertificatepath

I would assume that permissions may also come into play later.

Closing since this is a configuration problem and not a issue with the image.
