### ISSUE TITLE
Can't use HTTP/2 under alpine/httpd in browsers

### ISSUE THREAD

**Issue by plysrh** [docker-library/httpd#50]
Hello, I can't use HTTP/2 protocol under alpine/httpd image. I add the arguments `--enable-ssl --enable-so --enable-http2` to `./configure` step and configure the httpd server with SSL and a self-signed certificate and adding the `Protocols h2 http/1.1` instruction.

When I tested the server with curl the result I think its just fine:
![image](https://cloud.githubusercontent.com/assets/10591025/25785852/52702bfe-3360-11e7-88d5-782c70812015.png)

But when I try with a browser (Chrome, Firefox, Safari) the result always its a `ERR_CONNECTION_CLOSED`:
![image](https://cloud.githubusercontent.com/assets/10591025/25785871/bcd498a4-3360-11e7-9d7b-04e61442257a.png)

I thought it could be the self-signed certificate the wrong one and I followed several ways to generate it, but I always got the same result in browsers. I finally try with the debian/httpd image and everything worked ok.

At the moment I will use the debian/httpd image but I would like to use the alpine/httpd image in the future.

What is wrong with the alpine/httpd image and the HTTP/2 protocol?

**Comment by ptaunton** [comment]
You will need an httpd server that supports ALPN. This means a minimum version of LibreSSL 2.5.x so the alpine/httpd image needs updating to use the 2.5.x stream of LibreSSL.

**Comment by yosifkit** [comment]
I thought that when we switched to alpine:3.5 that it was new enough. :cry:  But I guess that it will have to wait for alpine:3.6 (since alpine edge has 2.5.4 while alpine 3.5 [only has 2.4.4](https://pkgs.alpinelinux.org/packages?name=libressl&branch=&repo=&arch=&maintainer=) of libressl).

Alpine 3.6 should be coming out in the next few weeks. :pray:

**Comment by gfortaine** [comment]
@yosikift [Alpine 3.6.0 released](https://alpinelinux.org/posts/Alpine-3.6.0-released.html)
