### ISSUE TITLE
Update httpd:2.4 to version 2.4.26

### ISSUE THREAD

**Issue by larscheidt** [docker-library/httpd#56]
httpd version 2.4.26 was released two days ago, fixing 5 Important vulnerabilities: https://httpd.apache.org/security/vulnerabilities_24.html

**Comment by tianon** [comment]
Ouch!  I'll have a PR open shortly; thanks for the prod!

**Comment by tianon** [comment]
https://github.com/docker-library/httpd/pull/57 :+1:

**Comment by marvec** [comment]
openssl needs to get updated as well #62

**Comment by marvec** [comment]
Cannot build 2.4.26 on Alpine because of this https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220160
There is a patch available but I think the goal is to have a more robust solution. The only other option is to wait for the fix.
