### ISSUE TITLE
alpine 3.6 failing to build image 2.4.27

### ISSUE THREAD

**Issue by sudhakarpdf** [docker-library/httpd#67]
Could you please check failing with SSL issues.
https://doi-janky.infosiftr.net/job/update.sh/job/httpd/1240/console

**Comment by tianon** [comment]
See the discussion on https://github.com/docker-library/httpd/pull/57 -- I'll go open a new PR for just the Alpine bump now so we have a clean place to track this bump.

**Comment by tianon** [comment]
https://github.com/docker-library/httpd/pull/68 :+1:

**Comment by sudhakarpdf** [comment]
Thank you for help.  👍
