### ISSUE TITLE
2.4/alpine build for httpd fails sporadically with "gpg: keyserver receive failed"

### ISSUE THREAD

**Issue by nluetic** [docker-library/httpd#70]
When using the 2.4/alpine Dockerfile as is, when building I *sometimes* get:
```+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.PtzTUzm20r
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys A93D62ECC3C8EA12DB220EC934EA76E6791485A8
gpg: keybox '/tmp/tmp.PtzTUzm20r/pubring.kbx' created
gpg: keyserver receive failed: Address not available
```
Seems this problem occurs elsewhere too, see:
[gliderlabs, issue 306](https://github.com/gliderlabs/docker-alpine/issues/306) or [nodejs, issue 380](https://github.com/nodejs/docker-node/issues/380) for example.

Maybe some of the keyservers are not very reliable.

I did not find a way to make this reproducible. 

Unrelated to this, I think an `apk update` should be added before using any other apk commands.

**Comment by tianon** [comment]
Yes, we often see issues with different servers in the sks-keyservers pools (and occasionally issues with the DNS of sks-keyservers.net itself) -- ideally, mirrors with issues would be removed from the upstream pools, but that's not always feasible (or timely), so retrying (or trying other mirrors upon failure) are our only real options.
