### ISSUE TITLE
Enabling AllowOverride?

### ISSUE THREAD

**Issue by AlmogBaku** [docker-library/httpd#71]
it seems like it disabled by default for some reason?

```
bash-4.3# cat conf/httpd.conf  | grep AllowOverride
    AllowOverride none
    # AllowOverride controls what directives may be placed in .htaccess files.
    #   AllowOverride FileInfo AuthConfig Limit
    AllowOverride None
    AllowOverride None```

**Comment by tianon** [comment]
If you look at our `Dockerfile` (https://github.com/docker-library/httpd/blob/f9298751fa0051fae5f09c61e778d77861e551a6/2.4/Dockerfile), we don't modify the default configuration from upstream in any substantial way besides adjusting logs to go to stdout/stderr, as is standard Docker practice:

https://github.com/docker-library/httpd/blob/f9298751fa0051fae5f09c61e778d77861e551a6/2.4/Dockerfile#L137-L140

So this default value for `AllowOverride` is coming directly from upstream's own defaults, and if it doesn't match what you need for your project, you'll probably want to write a short `Dockerfile` to adjust it. :+1:
