### ISSUE TITLE
Adding support for applying patches

### ISSUE THREAD

**Issue by ScottSorrentino** [docker-library/httpd#75]
For both the 2.2 and 2.4 series container images, it appears that the Apache HTTP Server project has released patches that apply to the source versions being compiled:

http://www.apache.org/dist/httpd/patches/apply_to_2.2.34/
http://www.apache.org/dist/httpd/patches/apply_to_2.4.27/

It would be great if there was a mechanism for bringing in these patches as part of the Docker build process.  In the case of the 2.2 series, it's not clear there will ever be any newer releases from upstream.

**Comment by ScottSorrentino** [comment]
I have taken two different approaches to this, represented by PR #76 and #77.  Would love thoughts/feedback on either, or whether there are other options.  With both approaches, I tried to make it easy to update the base Apache package in the future without needing to rip out a bunch of version-specific patch statements in the RUN commands.

For #76, the patches would need to be downloaded and added to this repository into version-specific sub-directories.  Ordering of patch application relies on directory timestamp.  If there's no version-specific subdirectory, the patch step is a no-op.

The second approach (#77) uses a text file to list the patches and their checksums.  Patches are downloaded at build time and checksums validated.  Patches are applied in the order they appear.  When changing the base Apache release, this one file would need to be cleared out.

In both cases, someone still needs to track patches released by upstream between official releases and either download/add them to the repository or add their data to the PATCHES file.

**Comment by tianon** [comment]
It's terrifyingly disappointing to see these files provided as-is with no signatures or even published checksums. :disappointed:

Since these will need to be applied before we build `httpd`, any solution which applies them ought to avoid `COPY` (since it has odd and often inconsistent cache behavior), and likely ought to just be based on `./update.sh` scraping the list of URLs and embedding them directly into the `Dockerfile` itself (perhaps via `ENV HTTPD_PATCH_URLS ...` or something like that), to be downloaded at build time.

The `httpd` source tarball has a signature we can verify after downloading, but these patch files have neither signatures nor published checksums, so their provenance cannot be easily verified, nor even their proper transmission.

**Comment by ScottSorrentino** [comment]
All good points.  It is unfortunate that no signatures or checksums are available for patches.  Though not perfect, a checksum could be recorded by `update.sh` to track what was seen when the Dockerfiles were modified.  This value could then be checked during the download/build process, if only to verify that the patch matched what was seen at the time the repository was updated.

I will incorporate this suggestion and submit it for comments.

**Comment by ScottSorrentino** [comment]
I've submitted #79 with this new approach.  Rather than setting environment variables and looping through them in each `Dockerfile` (looping assuming there's more than one patch), `update.sh` directly applies updates to the RUN command sequence.  Checksums, while not perfect, are verified based on the sum seen by `update.sh`.

Also interesting was the release of 2.4.28 during my testing.  Here's a case where the new sources were available a few days before the official announcement **and** there's still no "apply_to_2.4.28" patch tree.  The code in `update.sh` allows for this scenario when there are no patches to apply.

I do have a sample implementation that uses environment variables instead of modifying the RUN commands  I didn't like that one as much, but could make that available for comparison if needed.
