### ISSUE TITLE
add ErrorDocument 404 /errors/not_found.html

### ISSUE THREAD

**Issue by symoN5** [docker-library/httpd#82]
Hello, 

I just want to add a 404 error document. 
This line of config
`ErrorDocument 404 /errors/not_found.html`

But where to found the **"real" httpd.conf** to then run 

_`COPY ./my-httpd.conf /usr/local/apache2/conf/httpd.conf`_

Can you please help me? Thanks in advance!

**Comment by yosifkit** [comment]
I am not suite sure what you are asking.  `/usr/local/apache2/conf/httpd.conf` is the correct location for the real config file. You'd also need to make sure that your `not_found.html` (and any other files) get copied or mounted into the container.
