### ISSUE TITLE
Update to Debian 9 "Stretch"

### ISSUE THREAD

**Issue by urzds** [docker-library/httpd#84]
Debian 9 "Stretch" was released this summer, while this image is still using Debian 8 "Jessie". It would be nice, if this could be updated, to satisfy dependencies of software installed on top of the Apache HTTP Server.

**Comment by tianon** [comment]
We probably have to do something transitional like what's proposed over in https://github.com/docker-library/php/issues/504 in order to do this in a way that gives users time to adjust before we potentially break their usage.

**Comment by cpjolly** [comment]
@tianon - yes, that sounds like the right approach. Any idea when this will be implemented & Debian 9 "Stretch" will be available ?

Debian 8  "Jessie" transitions from full support to LTS on June 6th 2018, so we should aim to have it available latest by then.

**Comment by J0WI** [comment]
This would also fix #98

**Comment by andrin55** [comment]
Any updates on this?

**Comment by J0WI** [comment]
I've just opened #113

**Comment by J0WI** [comment]
This has been fixed in #113
