### ISSUE TITLE
Server Side Includes not enabled

### ISSUE THREAD

**Issue by jburtondev** [docker-library/httpd#86]
Firstly, thanks for this image. It works great. 

**My issue is related to enabling Server Side Includes,** which is not working by default as per the usual Apache setup. Can anyone shed some light on how to enable this? 

Disclaimer: I know SSI's are generally avoided for various reasons. 

Thanks, 
Jamie

**Comment by TheMeier** [comment]
As the documentation (https://hub.docker.com/_/httpd/) states:


```
Configuration
To customize the configuration of the httpd server, just COPY your custom configuration in as /usr/local/apache2/conf/httpd.conf.


```

**Comment by jburtondev** [comment]
@TheMeier great, thanks.

**Comment by tianon** [comment]
Closing, since this appears solved!
