### ISSUE TITLE
Suexec user mismatch

### ISSUE THREAD

**Issue by xdraylin** [docker-library/httpd#89]
When trying to execute a cgi-file, suexec throws an error, because the apache process is running as user "daemon", whilst the flag "AP_HTTPD_USER" is set to "www" by default.

Error-message:
[2018-01-31 09:20:16]: user mismatch (daemon instead of www)

Output of ps -e:
PID   USER     TIME   COMMAND
    1 root       0:00 httpd -DFOREGROUND
    8 daemon        0:00 httpd -DFOREGROUND
    9 daemon        0:00 httpd -DFOREGROUND

Output of suexec -V:
 -D AP_DOC_ROOT="/usr/local/apache2/htdocs"
 -D AP_GID_MIN=100
 -D AP_HTTPD_USER="www"
 -D AP_LOG_EXEC="/usr/local/apache2/logs/suexec_log"
 -D AP_SAFE_PATH="/usr/local/bin:/usr/bin:/bin"
 -D AP_UID_MIN=100
 -D AP_USERDIR_SUFFIX="public_html"

**Comment by tianon** [comment]
This is a mismatch in the default configuration provided by the httpd project directly -- we don't modify either the `User` directive in the `httpd.conf` file they provide nor the default value of `AP_HTTPD_USER` (which as I understand it is compiled-in).

To get this working, you'll need to either modify the `User` directive in the `httpd.conf` provided by upstream, or reconfigure `suexec` to use a different username (https://httpd.apache.org/docs/2.4/mod/mod_suexec.html, `SuexecUserGroup`).
