### ISSUE TITLE
Container exits on SIGWINCH

### ISSUE THREAD

**Issue by ChestersGarage** [docker-library/httpd#9]
Hello,

In -it mode, the container exited just by me opening a new tab in the terminal window (Ubuntu 14.04 host).  Logged output:

[Fri Dec 25 02:41:50.249974 2015] [mpm_event:notice] [pid 1:tid 139752883230592] AH00492: caught SIGWINCH, shutting down gracefully

Thanks!

**Comment by yosifkit** [comment]
I think this is an issue of how `httpd` handles this particular signal. Is there a need to run it interactively? Or would `-d` instead of `-it` followed by a `docker logs --follow myhttpd`

**Comment by tianon** [comment]
Even just dropping "-t" should remove the sending of SIGWINCH when the
window resizes.

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/docs/issues/669 to update the image description to avoid this issue.

**Comment by russau** [comment]
From the ASF Bugzilla - commenting here with the hopes it saves the next person debugging this some time!

> You are correct that SIGWINCH is used to signal a windows size change to the applications running on a terminal. Due to the lack of other signal numbers and given the fact that httpd normally runs detached from a terminal the SIGWINCH signal was chosen to instruct httpd to do a graceful shutdown. So this works as designed.

https://bz.apache.org/bugzilla/show_bug.cgi?id=50669
