### ISSUE TITLE
Unable to pull httpd docker images

### ISSUE THREAD

**Issue by ryanschuhler** [docker-library/httpd#93]
Right now when I run `docker pull httpd` I get the following error 

> Using default tag: latest
> latest: Pulling from library/httpd
> no matching manifest for linux/amd64 in the manifest list entries

Has something changed or broken in the library?

**Comment by Mikeks81** [comment]
same here for httpd:2.4-alpine

**Comment by yosifkit** [comment]
Duplicate of: https://github.com/docker-library/official-images/issues/3835
