### ISSUE TITLE
Update Alpine base to 3.7?

### ISSUE THREAD

**Issue by snw35** [docker-library/httpd#97]
Hi,

Wondering if it would be possible to update the Alpine base of the Alpine image to 3.7? I've cloned the repo and built it against 3.7 (literally just changed FROM alpine:3.6 to FROM alpine:3.7) and it builds and works fine for me, so it looks like no other changes are needed:

```
/usr/local/apache2 # cat /etc/alpine-release 
3.7.0
/usr/local/apache2 # wget -S localhost -O -
Connecting to localhost (127.0.0.1:80)
  HTTP/1.1 200 OK
  Date: Sun, 01 Apr 2018 12:25:49 GMT
  Server: Apache/2.4.33 (Unix)
  Last-Modified: Mon, 11 Jun 2007 18:53:14 GMT
  ETag: "2d-432a5e4a73a80"
  Accept-Ranges: bytes
  Content-Length: 45
  Connection: close
  Content-Type: text/html
  
<html><body><h1>It works!</h1></body></html>
-                    100% |*******************************|    45   0:00:00 ETA
/usr/local/apache2 # 
```

I'd like to switch to using this as a base instead of installing httpd in Alpine manually, but the packages in my image are 3.7 based.

I realize the same applies in the other direction though - would you not want to do this in case it breaks compatibility with images that have already used this and inherited 3.6 as a base?

If so, would the answer be creating a new -alpine37 tag, or having a cut-off at a certain version of httpd where all images beyond that are 3.7?

Thanks!

**Comment by J0WI** [comment]
This has been fixed in https://github.com/docker-library/httpd/commit/eaf4c70fb21f167f77e0c9d4b6f8b8635b1cb4b6.
